Removed unused method (#5219)
Fixes src\main\java\org\jabref\model\bibtexkeypattern\AbstractBibtexKeyPattern.java:60: error: [CollectionIncompatibleType] Argument 'type' should not be passed to this method; its type String is not compatible with its collection's type argument EntryType
        data.remove(type);
                   ^
    (see https://errorprone.info/bugpattern/CollectionIncompatibleType)

Former-commit-id: 8f463e4137a65e512c08700615b11a0c42706d4c